//===========================================================================
//
// Name:			default_c.c
// Programmer:		Ryan Feltrin (ryan@gmistudios.com)
// version:			1
// Tab Size:		4 (real tabs)
//===========================================================================

#include "botfiles/chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"WolfBot"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.15
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/default_w.c"
	CHARACTERISTIC_AIM_SKILL					0.5
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_VIEW_FACTOR					0.25
	CHARACTERISTIC_VIEW_MAXCHANGE				100
	CHARACTERISTIC_REACTIONTIME					0.6
	CHARACTERISTIC_FIRETHROTTLE					0.4

	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.7
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_ACCURACY_SNIPERRIFLE		0.7
	CHARACTERISTIC_AIM_SKILL_SNIPERRIFLE		0.4
	CHARACTERISTIC_AIM_ACCURACY_FLAMETHROWER	0.2
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.7
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.7

	CHARACTERISTIC_CHAT_FILE					"bots/default_t.c"
	CHARACTERISTIC_CHAT_NAME					"WolfBot"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.4

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.3
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/default_i.c"
	CHARACTERISTIC_AGGRESSION					0.3
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}

skill 2
{
	CHARACTERISTIC_NAME							"WolfBot"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.35
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/default_w.c"
	CHARACTERISTIC_AIM_SKILL					0.6
	CHARACTERISTIC_AIM_ACCURACY					0.6
	CHARACTERISTIC_VIEW_FACTOR					0.25
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					0.4
	CHARACTERISTIC_FIRETHROTTLE					0.25

	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_ACCURACY_SNIPERRIFLE		0.73
	CHARACTERISTIC_AIM_SKILL_SNIPERRIFLE		0.5
	CHARACTERISTIC_AIM_ACCURACY_FLAMETHROWER	0.2
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.7
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.7

	CHARACTERISTIC_CHAT_FILE					"bots/default_t.c"
	CHARACTERISTIC_CHAT_NAME					"WolfBot"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.4

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.3
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/default_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}

skill 3
{
	CHARACTERISTIC_NAME							"WolfBot"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.4
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/default_w.c"
	CHARACTERISTIC_AIM_SKILL					0.65
	CHARACTERISTIC_AIM_ACCURACY					0.65
	CHARACTERISTIC_VIEW_FACTOR					0.25
	CHARACTERISTIC_VIEW_MAXCHANGE				220
	CHARACTERISTIC_REACTIONTIME					0.3
	CHARACTERISTIC_FIRETHROTTLE					0.25

	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_ACCURACY_SNIPERRIFLE		0.78
	CHARACTERISTIC_AIM_SKILL_SNIPERRIFLE		0.6
	CHARACTERISTIC_AIM_ACCURACY_FLAMETHROWER	0.2
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.7
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.7

	CHARACTERISTIC_CHAT_FILE					"bots/default_t.c"
	CHARACTERISTIC_CHAT_NAME					"WolfBot"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.4

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.3
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/default_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}

skill 4
{
	CHARACTERISTIC_NAME							"WolfBot"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.8
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/default_w.c"
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_ACCURACY					0.8
	CHARACTERISTIC_VIEW_FACTOR					0.25
	CHARACTERISTIC_VIEW_MAXCHANGE				250
	CHARACTERISTIC_REACTIONTIME					0.2
	CHARACTERISTIC_FIRETHROTTLE					0.2

	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.9
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_ACCURACY_SNIPERRIFLE		0.82
	CHARACTERISTIC_AIM_SKILL_SNIPERRIFLE		0.7
	CHARACTERISTIC_AIM_ACCURACY_FLAMETHROWER	0.2
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.7
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.7

	CHARACTERISTIC_CHAT_FILE					"bots/default_t.c"
	CHARACTERISTIC_CHAT_NAME					"WolfBot"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.4

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.3
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/default_i.c"
	CHARACTERISTIC_AGGRESSION					0.3
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}
